config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from store_apps.products.views import CategoryListView

urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls[:2], namespace=admin.site.urls[2])),
    url(r'^products/', include(("store_apps.products.urls", 'products'), namespace="products")),
    url(r'^users/', include(("store_apps.users.urls", 'users'), namespace="users")),
    url(r'^payments/', include(("store_apps.payments.urls", 'payments'), namespace="payments")),
]

if settings.DEBUG is False:
    import debug_toolbar

    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store_apps/payments/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include
from store_apps.payments import views

urlpatterns = [
    url(r'^order/pay/$', views.OrderPayView.as_view(), name='order_pay'),
    url(r'^orders/$', views.OrderListView.as_view(), name='order_list'),
    url(r'^order/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order_detail'),
]

store_apps/products/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include
from store_apps.products import views

urlpatterns = [
    url(r'^$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^cart/$', views.CartView.as_view(), name='cart'),
    url(r'^(?P<product_pk>[0-9]+)/like/$', views.LikeToggleView.as_view(), name='like_toggle'),
    url(r'^(?P<product_pk>[0-9]+)/add/to/cart/$', views.AddToCartView.as_view(), name='add_to_cart'),
    url(r'^(?P<category_slug>.+)/(?P<product_slug>.+)/$', views.ProductDetailView.as_view(), name='product_detail'),
    url(r'^(?P<category_slug>.+)/(?P<product_slug>.+)/leave/comment$', views.AddCommentToProduct.as_view(),
        name='add_comment'),
    url(r'^(?P<category_slug>.+)/$', views.CategoryDetailView.as_view(), name='category_detail'),
]

store_apps/users/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
]

store_apps/payments/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='customer', null=True, on_delete=models.SET_NULL)
    stripe_id = models.CharField(_('Stripe id'), max_length=50, blank=True)

    def __str__(self):
        return f'{self.user}'


class Order(TimeStampedModel):
    STATUSES = Choices(
        ('succeeded', _('Succeeded')),
        ('pending', _('Pending')),
        ('failed', _('Failed')),
    )

    customer = models.ForeignKey(Customer, related_name='orders', null=True, on_delete=models.SET_NULL)
    amount = models.PositiveIntegerField(_('Amount'))
    status = models.CharField(_('Status'), max_length=15, choices=STATUSES, default=STATUSES.pending)
    address = models.CharField(max_length=255)

    def __str__(self):
        return f'Order {self.id} by {self.customer}'

    def get_absolute_url(self):
        return reverse('payments:order_detail', kwargs={'pk': self.pk})

store_apps/users/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from model_utils import Choices


@python_2_unicode_compatible
class User(AbstractUser):
    ACTIVITY_PARAM = 'activity'
    ACTIVITY_OPTIONS = Choices(
        ('no_like', _('No like')),
        ('no_comment', _('No comment')),
        ('no_like_and_no_comment', _('No like and comment')),
    )

    def __str__(self):
        return self.username

store_apps/payments/forms.py
from django import forms


class OrderPayForm(forms.Form):
    stripe_token = forms.CharField(max_length=100, widget=forms.HiddenInput)
    address = forms.CharField(max_length=255)

store_apps/products/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from config import settings
from store_apps.products.models import Like, Product, Comment, Cart

User = get_user_model()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }


class AddToCartForm(forms.Form):
    product_quantity = forms.DecimalField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control'}))

store_apps/payments/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from store_apps.common.mixins import AdditionalMixin
from store_apps.payments.forms import OrderPayForm
from store_apps.payments.models import Order
from store_apps.payments.stripe_service import make_payment
from store_apps.products.models import Cart


class OrderPayView(FormView):
    template_name = 'payments/order_pay.html'
    form_class = OrderPayForm
    success_url = reverse_lazy('payments:order_list')
    extra_context = {'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY}

    user = None
    amount = None

    @method_decorator([login_required, csrf_exempt, ])
    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        self.amount = Cart.get_total_price(user=self.user)['price']
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = self.amount
        return context

    def form_valid(self, form):
        make_payment(self.request, self.user, form, self.amount)
        return HttpResponseRedirect(self.get_success_url())


class OrderListView(AdditionalMixin, ListView):
    model = Order
    template_name = 'payments/order_list.html'
    user = None

    @method_decorator([login_required, ])
    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Order.objects.filter(customer__user=self.user)


class OrderDetailView(AdditionalMixin, DetailView):
    model = Order
    template_name = 'payments/order_detail.html'

    @method_decorator([login_required, ])
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Order.objects.select_related('customer__user')

store_apps/products/views.py
import json
from collections import OrderedDict

from braces.views import JSONResponseMixin, AjaxResponseMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.signals import request_finished
from django.db import IntegrityError, DataError
from django.db import models
from django.db.models import Sum, Case, When, IntegerField, Count, F, Q, Subquery, OuterRef, Max, ExpressionWrapper
from django.db.models.functions import Coalesce
from django.dispatch import receiver
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse, resolve
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, FormView, TemplateView, View, CreateView
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin
from django_filters.views import FilterView

from store_apps.common.mixins import NewArrivalsMixin, CategoryMixin, AdditionalMixin, HitCounterMixin
from store_apps.common.utils import get_ip_from_request
from store_apps.products.filters import ProductFilter
from store_apps.products.forms import CommentForm, AddToCartForm
from store_apps.products.models import Category, Product, Like, Comment, HitCountBase, Cart


class CategoryListView(NewArrivalsMixin, HitCounterMixin, ListView):
    model = Category

    @staticmethod
    def get_ordered_grade_info():
        ids = Product.objects.annotate(Count('likes', distinct=True)).filter(
            Q(grade='base', likes__count__gt=10) | Q(grade='standard', likes__count__gt=5) | Q(
                grade='premium')).values('id')
        return list(
            Product.objects.values('grade').annotate(value=Count('id', distinct=True)).filter(id__in=ids).order_by())

    def get_queryset(self):
        return Category.objects.annotate(Count('products')).prefetch_related('products__likes', 'products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grade_list'] = self.get_ordered_grade_info()
        context['popular_products_list'] = Product.get_popular_products()
        context['hit_list'] = HitCountBase.hits_in_last_week()
        return context


class CategoryDetailView(AdditionalMixin, DetailView, MultipleObjectMixin):
    model = Category
    slug_url_kwarg = 'category_slug'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        object_list = self.object.products.all().prefetch_related('likes')
        object_list = ProductFilter(self.request.GET, queryset=object_list)
        context = super().get_context_data(object_list=object_list.qs.distinct(), product_filter=object_list, **kwargs)
        return context


class ProductDetailView(AdditionalMixin, DetailView):
    count_hit = True
    model = Product
    slug_url_kwarg = 'product_slug'
    category = None

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['form'] = AddToCartForm()
        context['comment_form'] = CommentForm()
        return context


class AddCommentToProduct(CreateView):
    http_method_names = ('post',)
    form_class = CommentForm
    product = None
    user = None

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, slug=kwargs['product_slug'])
        if self.request.user.is_authenticated:
            self.user = self.request.user
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.product = self.product
        instance.user = self.user
        if not self.user:
            instance.ip = get_ip_from_request(self.request)
        instance.save()
        return redirect(self.product.get_absolute_url())

    def form_invalid(self, form):
        return redirect(self.product.get_absolute_url())


class LikeToggleView(AjaxResponseMixin, JSONResponseMixin, View):
    http_method_names = ('post',)

    product = None
    user = None
    ip = None

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, pk=kwargs['product_pk'])
        if self.request.user.is_authenticated:
            self.user = self.request.user
        else:
            self.ip = get_ip_from_request(self.request)
        return super().dispatch(request, *args, **kwargs)

    def post_ajax(self, request, *args, **kwargs):
        like_obj, created = Like.objects.get_or_create(product=self.product, user=self.user, ip=self.ip)
        if not created:
            like_obj.delete()
        response = {'likes': self.product.count_likes()}
        return self.render_json_response(response)

    # def delete_ajax(self, request, *args, **kwargs):
    #     like_obj = Like.objects.get(product=self.product, user=self.user, ip=self.ip)



class AddToCartView(AjaxResponseMixin, JSONResponseMixin, FormView):
    http_method_names = ('post',)
    form_class = AddToCartForm

    product = None
    user = None

    @method_decorator([login_required, csrf_exempt, ])
    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, pk=kwargs['product_pk'])
        self.user = self.request.user
        return super().dispatch(request, *args, **kwargs)

    def get_context_dict(self):
        """ This method create a dict for json_response (to dump). """
        storage = messages.get_messages(self.request)
        message_list = [{"message": message.message, "tags": message.tags} for message in storage]
        context_dict = {'items_in_cart': Cart.objects.filter(user=self.user).count(), 'messages': message_list}
        return context_dict

    def post_ajax(self, request, *args, **kwargs):
        form = AddToCartForm(request.POST)
        if form.is_valid():  # todo add handle django.db.utils.DataError (too long)
            try:
                Cart.objects.create(product=self.product, user=self.user,
                                    product_quantity=form.cleaned_data['product_quantity'])
                messages.success(request, 'Added new item to cart.')
            except DataError:
                messages.error(request, 'Too many item quantity. Try to enter less.')
        return self.render_json_response(self.get_context_dict())

    # def delete_ajax(self, request, *args, **kwargs): or (class DeleteAllFromCartView and DeleteItemFromCartView)


class CartView(AdditionalMixin, TemplateView):
    template_name = 'products/cart.html'

    user = None

    @method_decorator([login_required, ])
    def dispatch(self, request, *args, **kwargs):
        self.user = self.request.user
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_list = Cart.objects.filter(user=self.user).select_related('product')
        if cart_list:
            context['cart_list'] = cart_list
            context['total_price'] = Cart.get_total_price(user=self.user)
        return context

store_apps/users/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

store_apps/templates/base.html
{% load humanize %}
{% load static i18n %}
{% load products_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <title>{% block title %}Store of Electronic parts.{% endblock title %}</title>

    {% block css %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
              integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
              crossorigin="anonymous">
        <!-- Latest compiled JavaScript -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">
        <link href="{% static 'css/products.css' %}" rel="stylesheet">
    {% endblock css %}

    {% block javascript %}
        <!--[if lt IE 9]>
        <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- Latest compiled JavaScript -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
                integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
</head>

<body>
<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="d-flex justify-content-start align-items-center">
                <a class="blog-header-logo text-dark" href="{% url 'home' %}">Home</a>
                {% block category %}
                    {% for category in category_list %}
                        <a class="m-3 font-italic text-dark" href="{{ category.get_absolute_url }}">{{ category.name|title }}
                            <span class="badge badge-secondary" id="items_in_cart">{{ category.products__count|intcomma }}</span>
                        </a>
                    {% endfor %}
                {% endblock category %}
            </div>
            <div class="d-flex justify-content-end align-items-center">
                {% if request.user.is_authenticated %}
                    <a class="m-3 font-italic text-dark" href="{% url 'payments:order_list' %}">Orders</a>
                    <a class="m-3 font-italic text-dark" href="{% url 'products:cart' %}">Cart
                        <span class="badge badge-secondary" id="items_in_cart">{% items_in_cart request.user %}</span>
                    </a>
                    <h3 class="m-3 font-italic">{{ request.user.username|title }}</h3>
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </header>


    <ul id="messages">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
    </ul>

    <main class="main">
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>

    {% block new_arrivals %}
        {% include 'products/new_arrivals.html' %}
    {% endblock new_arrivals %}
</div>

<footer class="blog-footer mt-5">
        <a class="text-dark" href="https://www.linkedin.com/in/fabel/">Fabel</a>.
</footer>

</body>
</html>

store_apps/templates/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    {% if form.errors and not form.non_field_errors %}
        <p class="errornote">
            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                {% trans "Please correct the errors below." %}{% endif %}
        </p>
    {% endif %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="errornote">
                {{ error }}
            </p>
        {% endfor %}
    {% endif %}

    <div id="content-main">

        {% if user.is_authenticated %}
            <p class="errornote">
                {% blocktrans trimmed %}
                    You are authenticated as {{ username }}, but are not authorized to
                    access this page. Would you like to login to a different account?
                {% endblocktrans %}
            </p>
        {% endif %}

        <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
            <div class="form-row">
                {{ form.username.errors }}
                {{ form.username.label_tag }} {{ form.username }}
            </div>
            <div class="form-row">
                {{ form.password.errors }}
                {{ form.password.label_tag }} {{ form.password }}
                <input type="hidden" name="next" value="{{ next }}"/>
            </div>
            {% url 'admin_password_reset' as password_reset_url %}
            {% if password_reset_url %}
                <div class="password-reset-link">
                    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
                </div>
            {% endif %}
            <div class="submit-row">
                <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}"/>
            </div>
        </form>

    </div>
{% endblock %}