config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from store_apps.products.views import CategoryListView

urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls[:2], namespace=admin.site.urls[2])),
    url(r'^products/', include(("store_apps.products.urls", 'products'), namespace="products")),
    url(r'^users/', include(("store_apps.users.urls", 'users'), namespace="users")),
    url(r'^payments/', include(("store_apps.payments.urls", 'payments'), namespace="payments")),
]

if settings.DEBUG is False:
    import debug_toolbar

    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store_apps/payments/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include
from store_apps.payments import views

urlpatterns = [
    url(r'^order/pay/$', views.OrderPayView.as_view(), name='order_pay'),
    url(r'^orders/$', views.OrderListView.as_view(), name='order_list'),
    url(r'^order/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order_detail'),
]

store_apps/products/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include
from store_apps.products import views

urlpatterns = [
    url(r'^$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^cart/$', views.CartView.as_view(), name='cart'),
    url(r'^(?P<product_pk>[0-9]+)/like/$', views.LikeToggleView.as_view(), name='like_toggle'),
    url(r'^(?P<product_pk>[0-9]+)/add/to/cart/$', views.AddToCartView.as_view(), name='add_to_cart'),
    url(r'^(?P<category_slug>.+)/(?P<product_slug>.+)/$', views.ProductDetailView.as_view(), name='product_detail'),
    url(r'^(?P<category_slug>.+)/(?P<product_slug>.+)/leave/comment$', views.AddCommentToProduct.as_view(),
        name='add_comment'),
    url(r'^(?P<category_slug>.+)/$', views.CategoryDetailView.as_view(), name='category_detail'),
]

store_apps/users/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
]

store_apps/payments/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='customer', null=True, on_delete=models.SET_NULL)
    stripe_id = models.CharField(_('Stripe id'), max_length=50, blank=True)

    def __str__(self):
        return f'{self.user}'


class Order(TimeStampedModel):
    STATUSES = Choices(
        ('succeeded', _('Succeeded')),
        ('pending', _('Pending')),
        ('failed', _('Failed')),
    )

    customer = models.ForeignKey(Customer, related_name='orders', null=True, on_delete=models.SET_NULL)
    amount = models.PositiveIntegerField(_('Amount'))
    status = models.CharField(_('Status'), max_length=15, choices=STATUSES, default=STATUSES.pending)
    address = models.CharField(max_length=255)

    def __str__(self):
        return f'Order {self.id} by {self.customer}'

    def get_absolute_url(self):
        return reverse('payments:order_detail', kwargs={'pk': self.pk})

store_apps/products/models.py
from decimal import Decimal

from ckeditor.fields import RichTextField
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Count, F, Sum, ExpressionWrapper
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from model_utils import Choices
from model_utils.models import TimeStampedModel

from config import settings
from store_apps.common.utils import generate_unique_slug


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=200)
    slug = models.SlugField(_('Slug'), unique=True)

    PARAMS = Choices(
        ('following', 'following'),
        ('price_to', 'price_to'),
        ('price_from', 'price_from'),
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:category_detail', kwargs={'category_slug': self.slug})


class Product(TimeStampedModel):
    GRADE_CHOICES = Choices(
        ('base', 'base', _('Base')),
        ('standard', 'standard', _('Standard')),
        ('premium', 'premium', _('Premium')),
    )

    name = models.CharField(_('Name'), max_length=200)
    slug = models.SlugField(_('Slug'), unique=True)
    price = models.DecimalField(_('Price'), decimal_places=2, max_digits=9,
                                validators=[MinValueValidator(Decimal('0.01'))])
    description = RichTextField(_('Description'), blank=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    image = models.ImageField(_('Image'), upload_to='products/images/%Y/%m/%d', null=True)
    image_thumbnail = ImageSpecField(source='image',
                                     processors=[ResizeToFill(250, 270)],
                                     format='JPEG',
                                     options={'quality': 60})
    popular = models.BooleanField(_('Popular'))
    grade = models.CharField(max_length=15, choices=GRADE_CHOICES,
                             default='standard')

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = generate_unique_slug(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product_detail',
                       kwargs={'category_slug': self.category.slug, 'product_slug': self.slug})


    def add_comment_url(self):
        """ Returns a link to add a comment. """
        return reverse('products:add_comment',
                       kwargs={'category_slug': self.category.slug, 'product_slug': self.slug})

    def add_like_url(self):
        """ Returns a link to add a like. """
        return reverse('products:like_toggle',
                       kwargs={'product_pk': self.pk})

    def add_to_cart_url(self):
        """ Returns a link to add to cart. """
        return reverse('products:add_to_cart',
                       kwargs={'product_pk': self.pk})

    def get_recent_comments(self):
        """ Get all recent comments (for the last 24hours) """
        return self.comments.filter(modified__gte=timezone.now() - timezone.timedelta(days=1))

    def count_likes(self):
        return self.likes.count()

    @classmethod
    def get_popular_products(cls, limit: int = 10):
        """ Returns a list of [limit] items. That contains all products tagged popular and products with the most likes """
        return cls.objects.annotate(likes_count=Count('likes')).order_by('-popular', '-likes_count') \
                   .select_related('category').prefetch_related('likes')[:limit]


class Like(TimeStampedModel):
    product = models.ForeignKey(Product, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='likes',
                             on_delete=models.CASCADE)
    ip = models.GenericIPAddressField(blank=True, null=True)

    class Meta:
        unique_together = (('product', 'user'), ('product', 'ip'))

    def __str__(self):
        return '{} from {}'.format(self.product, self.user or self.ip)


class Comment(TimeStampedModel):
    product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='comments',
                             on_delete=models.CASCADE)
    ip = models.GenericIPAddressField(blank=True, null=True)
    text = models.CharField(_('Comment'), max_length=500, help_text='max comment length 500 characters')

    class Meta:
        ordering = ['-modified']

    def __str__(self):
        return 'Comment from {}'.format(self.user or self.ip)

    def get_absolute_url(self):
        return reverse('products:product_detail',
                       kwargs={'category_slug': self.product.category.slug, 'product_slug': self.product.slug})


class HitCountBase(models.Model):
    """ Model that stores the hit totals for Page by unique Day and (unique IP or unique User). """
    hits = models.PositiveIntegerField(default=0)
    page_url = models.URLField(verbose_name='Page url')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='hits',
                             on_delete=models.CASCADE)
    ip = models.GenericIPAddressField(blank=True, null=True)
    pub_date = models.DateField(default=timezone.localdate)

    class Meta:
        unique_together = (('user', 'page_url', 'pub_date'), ('ip', 'page_url', 'pub_date'),)

    def __str__(self):
        return '{} hits from {} to page: {}'.format(self.hits, self.user or self.ip, self.page_url)

    def increase(self):
        self.hits = F('hits') + 1
        self.save()

    @classmethod
    def hits_in_last_week(cls):
        """ Returns hit count for each day in week. """
        period = timezone.now().date() - timezone.timedelta(days=6)
        return cls.objects.filter(pub_date__gte=period).values('pub_date').annotate(Sum('hits')).order_by('pub_date')


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='carts',
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='carts', on_delete=models.CASCADE)
    product_quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{} from {}'.format(self.product, self.user)

    @classmethod
    def get_total_price(cls, user):
        return cls.objects.filter(user=user).select_related('product') \
            .aggregate(price=ExpressionWrapper(Sum(F('product__price') * F('product_quantity')),
                                               output_field=models.FloatField()))

store_apps/users/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from model_utils import Choices


@python_2_unicode_compatible
class User(AbstractUser):
    ACTIVITY_PARAM = 'activity'
    ACTIVITY_OPTIONS = Choices(
        ('no_like', _('No like')),
        ('no_comment', _('No comment')),
        ('no_like_and_no_comment', _('No like and comment')),
    )

    def __str__(self):
        return self.username

store_apps/payments/forms.py
from django import forms


class OrderPayForm(forms.Form):
    stripe_token = forms.CharField(max_length=100, widget=forms.HiddenInput)
    address = forms.CharField(max_length=255)

store_apps/products/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from config import settings
from store_apps.products.models import Like, Product, Comment, Cart

User = get_user_model()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }


class AddToCartForm(forms.Form):
    product_quantity = forms.DecimalField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control'}))

store_apps/payments/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from store_apps.common.mixins import AdditionalMixin
from store_apps.payments.forms import OrderPayForm
from store_apps.payments.models import Order
from store_apps.payments.stripe_service import make_payment
from store_apps.products.models import Cart


class OrderPayView(FormView):
    template_name = 'payments/order_pay.html'
    form_class = OrderPayForm
    success_url = reverse_lazy('payments:order_list')
    extra_context = {'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY}

    user = None
    amount = None

    @method_decorator([login_required, csrf_exempt, ])
    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        self.amount = Cart.get_total_price(user=self.user)['price']
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = self.amount
        return context

    def form_valid(self, form):
        make_payment(self.request, self.user, form, self.amount)
        return HttpResponseRedirect(self.get_success_url())


class OrderListView(AdditionalMixin, ListView):
    model = Order
    template_name = 'payments/order_list.html'
    user = None

    @method_decorator([login_required, ])
    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Order.objects.filter(customer__user=self.user)


class OrderDetailView(AdditionalMixin, DetailView):
    model = Order
    template_name = 'payments/order_detail.html'

    @method_decorator([login_required, ])
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Order.objects.select_related('customer__user')

store_apps/users/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

store_apps/templates/products/cart.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    {% if cart_list %}
        <h3 class="pb-4 my-3 font-italic">Cart</h3>
        <div class="row mb-2">
            {% for cart in cart_list %}
                <div class="col-md-6">
                    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-270 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <h4 class="mb-0">{{ cart.product.name|title }}</h4>
                            <p class="my-3">Price {{ cart.product.price }}</p>
                            <p class="my-3">Quantity {{ cart.product_quantity }}</p>
                            <a href="{{ cart.product.get_absolute_url }}" class="stretched-link">Look details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <hr>

        <div class="row">
            <div class="m-3">
                <h3 class="pb-4 font-italic">Total: {{ total_price.price }}</h3>
            </div>
            <div class="m-3">
                <a class="btn btn-outline-success" href="{% url 'payments:order_pay' %}">Pay</a>
            </div>
        </div>
    {% else %}
        <h3 class="pb-4 my-3 font-italic">Cart empty...</h3>
    {% endif %}



{% endblock %}

store_apps/templates/products/category_detail.html
{% extends "products/category_list.html" %}
{% load products_extras %}
{% load humanize %}

{#{% block category %}#}
{#    <div class="nav-scroller py-1 my-3">#}
{#        <nav class="nav">#}
{#            <h3 class="mr-5 font-italic ">Categories</h3>#}
{#            {% for category_ in category_list %}#}
{#                {% if category_.name == category.name %}#}
{#                    <a class="p-2 mx-3 text-dark"#}
{#                               href="{{ category_.get_absolute_url }}"><strong>{{ category_.name|title }}</strong>#}
{#                        <small class="text-muted">/ {{ category_.count_products_in_category|intcomma }}</small></a>#}
{#                {% else %}#}
{#                    <a class="p-2 mx-3 text-dark"#}
{#                       href="{{ category_.get_absolute_url }}">{{ category_.name|title }}#}
{#                        <small class="text-muted">/ {{ category_.count_products_in_category|intcomma }}</small></a>#}
{#                {% endif %}#}
{#            {% endfor %}#}
{#        </nav>#}
{#    </div>#}
{##}
{#    <hr>#}
{#{% endblock category %}#}

{% block content %}

    {% block product_filter %}
        <form action="" method="GET">
            {{ product_filter.form.as_p }}

            <button class="mx-3 btn btn-outline-success" type="submit">Search</button>
            <a class="btn btn-secondary my-2" href="{{ category.get_absolute_url }}">Reset</a>

        </form>
    {% endblock %}


    <hr>

    {% block products %}
        <div class="row mb-2">
            {% for product in object_list %}
                <div class="col-md-6">
                    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-270 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block mb-2 text-dark">{{ product.category.name|title }}</strong>
                            <h4 class="mb-0">{{ product.name|title }}</h4>
                            <h4 class="my-3">Price {{ product.price }}</h4>
                            <div class="mb-1 text-muted">Likes {{ product.count_likes }}</div>
                            <p class="card-text mb-auto">{{ product.description|truncatewords:15|safe|title }}</p>
                            <a href="{{ product.get_absolute_url }}" class="stretched-link">Look details</a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <img src="{{ product.image_thumbnail.url }}" class="card-img-top" width="250" height="270"
                                 alt="image: {{ product.name }}">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    {% endblock %}

    {% block paginator %}
        <div class="text-center">
            {% if page_obj.paginator.num_pages > 1 %}
                {% if page_obj.has_previous %}
                    <a href="{% relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}">previous</a>
                {% endif %}
                <span>page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                {% if page_obj.has_next %}
                    <a href="{% relative_url page_obj.next_page_number 'page' request.GET.urlencode %}">next</a>
                {% endif %}
            {% endif %}
        </div>
    {% endblock %}

{% endblock content %}

store_apps/templates/products/category_list.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}

    {% block popular_products %}
        <h3 class="pb-4 my-3 font-italic">Popular products</h3>
        <div class="row mb-2">
            {% for product in popular_products_list %}
                <div class="col-md-6">
                    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-270 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block mb-2 text-dark">{{ product.category.name|title }}</strong>
                            <h4 class="mb-0">{{ product.name|title }}</h4>
                            <h4 class="my-3">Price {{ product.price }}</h4>
                            <div class="mb-1 text-muted">Likes {{ product.count_likes }}</div>
                            <p class="card-text mb-auto">{{ product.description|truncatewords:15|safe|title }}</p>
                            <a href="{{ product.get_absolute_url }}" class="stretched-link">Look details</a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <img src="{{ product.image_thumbnail.url }}" class="card-img-top" width="250" height="270"
                                 alt="image: {{ product.name }}">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock popular_products %}

    <hr>

    {% block choice_of_week %}
        <h3 class="pb-4 my-3 font-italic">Choice of the Week</h3>
        <div class="card-deck mb-3 text-center">
            {% for grade in grade_list %}
                <div class="card mb-4 shadow-sm">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ grade.grade|title }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ grade.value }} products</h1>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock choice_of_week %}

    <hr>

    {% block likes_of_week %}
        <h3 class="pb-4 my-3 font-italic">Likes of the Week</h3>
        <div class="card-deck mb-3 text-center">
            {% for hit in hit_list %}
                <div class="card mb-4 shadow-sm">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ hit.pub_date|date:"l" }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ hit.hits__sum }} visits</h1>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock likes_of_week %}

{% endblock content %}

store_apps/templates/products/comment_form.html
{% block comment_form %}
    <form action="{{ product.add_comment_url }}" method="POST">
        {% csrf_token %}
        {% if comment_form.errors %}
            <div class="alert alert-danger">
                {{ comment_form.errors }}
            </div>
        {% endif %}

        {{ comment_form.label }}
        {{ comment_form }}
        <button type="submit">Leave comment</button>
    </form>
{% endblock %}

store_apps/templates/products/new_arrivals.html
{% block new_arrivals %}

    <h3 class="pb-4 my-3 font-italic">New Arrivals</h3>
    <div class="row mb-2">
        {% for product in new_arrivals %}
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-270 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-dark">{{ product.category.name|title }}</strong>
                        <h4 class="mb-0">{{ product.name|title }}</h4>
                        <h4 class="my-3">Price {{ product.price }}</h4>
                        <div class="mb-1 text-muted">Likes {{ product.count_likes }}</div>
                        <p class="card-text mb-auto">{{ product.description|truncatewords:15|safe|title }}</p>
                        <a href="{{ product.get_absolute_url }}" class="stretched-link">Look details</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img src="{{ product.image_thumbnail.url }}" class="card-img-top" width="250" height="270"
                             alt="image: {{ product.name }}">
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

store_apps/templates/products/product_detail.html
{% extends "base.html" %}


{% block content %}
    <div class="row flex-nowrap justify-content-end align-items-center">
        <a class="my-3 btn btn-sm btn-outline-secondary" href="{{ product.category.get_absolute_url }}">Back</a>
    </div>

    {% block product_detail %}
        <div class="row featurette my-4">
            <div class="col-md-7">
                <div class="mb-1 text-muted">{{ product.modified|date:"d M Y" }}</div>
                <h2 class="featurette-heading my-4">{{ product.name|title }}</h2>
                <h1 class="card-title pricing-card-title">Price {{ product.price }}</h1>
                <strong class="d-inline-block mb-2 text-dark">{{ product.category.name|title }}</strong>
                <p class="lead">{{ product.description|safe|title }}</p>

                {% if request.user.is_authenticated %}
                    <form id="cart-form" action="{{ product.add_to_cart_url }}" method="POST">
                        <div class="row">
                            <div class="mx-3">
                                <button class="btn btn-outline-secondary" type="submit">Add</button>
                            </div>
                            <div>
                                {{ form.product_quantity }}
                            </div>
                        </div>
                    </form>
                {% endif %}

            </div>
            <div class="col-md-5 border">
                <img src="{{ product.image.url }}" width="500" height="500" alt="image: {{ product.name }}">
            </div>
        </div>
    {% endblock product_detail %}

    <form id="like-form" class="like-form" action="{{ product.add_like_url }}" method="POST">
        <button class="btn btn-outline-secondary" type="submit">Like</button>
        <p id="likes-count" class="badge badge-secondary">{{ product.count_likes }}</p>
    </form>

    <hr>

    {% block comment_form %}
        {% include 'products/comment_form.html' %}
    {% endblock comment_form %}

    {% with product.get_recent_comments as comments %}
        {% if comments %}
            <h3>Comments...</h3>
            <ul class="list-group">
            {% for comment in comments %}
                <li class="list-group-item">
                    {{ comment.text|capfirst }}
                    {{ comment.modified }}
                    <br/>
                </li>
            {% endfor %}
        {% else %}
            <h3>No comments yet ...</h3>
        {% endif %}
    {% endwith %}
</ul>
{% endblock content %}